const tabs = [
    {
      key: "1",
      label: "Information Collection and Use",
      content: "While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally, identifiable information may include but is not limited to your name, email address, postal address, and phone number ('Personal Information')."
    },
    {
      key: "2",
      label: "Log Data",
      content: "Log data content goes here. It's often essential to log data in various applications to track user interactions, system events, and errors. Logging serves as a valuable tool for debugging, monitoring, and analyzing application behavior. In this section, we'll explore the importance of log data, its structure, and how it's utilized in different scenarios. When users interact with an application, such as browsing a website, submitting a form, or performing any action, the application may generate log data to record these activities. This log data typically includes timestamps, user IDs, event descriptions, and other relevant information. By logging such data, developers can gain insights into user behavior, identify patterns, and optimize the user experience. In addition to user interactions, applications also log system events and errors. These logs provide crucial information about the health and performance of the application. For example, system logs may capture CPU usage, memory consumption, network requests, and database queries. Error logs, on the other hand, document exceptions, crashes, and other issues encountered by the application. Log data is usually stored in log files or databases, depending on the logging mechanism employed by the application. Log files are plaintext files that contain chronological records of events, making them easy to parse and analyze. Log databases, such as Elasticsearch or Splunk, offer more advanced features like indexing, searching, and visualizing log data. Analyzing log data can uncover valuable insights into application performance, security vulnerabilities, and user engagement. Developers can use log analysis tools to filter, aggregate, and visualize log data, enabling them to detect anomalies, troubleshoot issues, and make data-driven decisions. In conclusion, log data plays a critical role in modern application development. By logging user interactions, system events, and errors, developers can gain valuable insights into application behavior and performance. Effective log management and analysis are essential for maintaining and improving the quality of applications in today's digital landscape. "
    },
    {
      key: "3",
      label: "Communication",
      content: "Log data content goes here. It's often essential to log data in various applications to track user interactions, system events, and errors. Logging serves as a valuable tool for debugging, monitoring, and analyzing application behavior. In this section, we'll explore the importance of log data, its structure, and how it's utilized in different scenarios. When users interact with an application, such as browsing a website, submitting a form, or performing any action, the application may generate log data to record these activities. This log data typically includes timestamps, user IDs, event descriptions, and other relevant information. By logging such data, developers can gain insights into user behavior, identify patterns, and optimize the user experience. In addition to user interactions, applications also log system events and errors. These logs provide crucial information about the health and performance of the application. For example, system logs may capture CPU usage, memory consumption, network requests, and database queries. Error logs, on the other hand, document exceptions, crashes, and other issues encountered by the application. Log data is usually stored in log files or databases, depending on the logging mechanism employed by the application. Log files are plaintext files that contain chronological records of events, making them easy to parse and analyze. Log databases, such as Elasticsearch or Splunk, offer more advanced features like indexing, searching, and visualizing log data. Analyzing log data can uncover valuable insights into application performance, security vulnerabilities, and user engagement. Developers can use log analysis tools to filter, aggregate, and visualize log data, enabling them to detect anomalies, troubleshoot issues, and make data-driven decisions. In conclusion, log data plays a critical role in modern application development. By logging user interactions, system events, and errors, developers can gain valuable insights into application behavior and performance. Effective log management and analysis are essential for maintaining and improving the quality of applications in today's digital landscape. "
    },
    {
    key: "4",
    label: "Cookies",
    content: "Cookies Feel free to reach out to us via email at contact@example.com or by filling out the contact form on our website. Our dedicated team is here to assist you with any inquiries, feedback, or concerns you may have regarding our products or services. Whether you have questions about placing an order, need assistance with a technical issue, or simply want to share your thoughts with us, we're committed to providing prompt and helpful support. Your satisfaction is our top priority, and we strive to ensure that every interaction with our customers is positive and productive. We value your input and are always looking for ways to improve our offerings, so don't hesitate to get in touch. We appreciate your interest in our company and look forward to hearing from you soon!"
    },
    {
    key: "5",
    label: "Security",
    content: "We reserve the right to modify, amend, or update this Privacy Policy at any time without prior notice, and such changes will become effective immediately upon posting on our website. It is your responsibility to review this Privacy Policy periodically to stay informed about any revisions. By continuing to use our website after any modifications to this Privacy Policy, you acknowledge and agree to be bound by the updated terms. We may notify you of changes to this Privacy Policy through email or by posting a prominent notice on our website. Your continued use of our website following the posting of changes constitutes acceptance of those changes. If you do not agree to the updated terms, you must immediately cease using our website and notify us of your decision. We encourage you to regularly check this page for any updates to ensure that you are aware of our latest privacy practices. We are committed to protecting your privacy and will not use your personal information in a manner materially different from what is described in this Privacy Policy without your consent. However, we may update this Privacy Policy from time to time to reflect changes in legal or regulatory requirements, industry best practices, or technological advancements. We encourage you to review this Privacy Policy periodically to stay informed about how we collect, use, and protect your personal information. Your continued use of our website following any changes to this Privacy Policy constitutes acceptance of those changes. If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us using the information provided below. We value your privacy and are committed to safeguarding your personal information. We may update this Privacy Policy periodically to reflect changes in our privacy practices or legal requirements. It is your responsibility to review this Privacy Policy periodically for updates. By continuing to use our website after any changes to this Privacy Policy, you acknowledge and agree to be bound by the updated terms. If you do not agree to the updated terms, you must immediately cease using our website and notify us of your decision. We are committed to protecting your privacy and will continue to take all necessary measures to ensure the security and confidentiality of your personal information. We encourage you to review this Privacy Policy periodically to stay informed about how we collect, use, and protect your personal information. Your continued use of our website following any changes to this Privacy Policy indicates your acceptance of those changes. If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us using the information provided below. We appreciate your trust in us and thank you for your continued support."
    },
    {
    key: "6",
    label: "Changes to This Privacy Policy",
    content: "We reserve the right to modify, amend, or update this Privacy Policy at any time without prior notice, and such changes will become effective immediately upon posting on our website. It is your responsibility to review this Privacy Policy periodically to stay informed about any revisions. By continuing to use our website after any modifications to this Privacy Policy, you acknowledge and agree to be bound by the updated terms. We may notify you of changes to this Privacy Policy through email or by posting a prominent notice on our website. Your continued use of our website following the posting of changes constitutes acceptance of those changes. If you do not agree to the updated terms, you must immediately cease using our website and notify us of your decision. We encourage you to regularly check this page for any updates to ensure that you are aware of our latest privacy practices. We are committed to protecting your privacy and will not use your personal information in a manner materially different from what is described in this Privacy Policy without your consent. However, we may update this Privacy Policy from time to time to reflect changes in legal or regulatory requirements, industry best practices, or technological advancements. We encourage you to review this Privacy Policy periodically to stay informed about how we collect, use, and protect your personal information. Your continued use of our website following any changes to this Privacy Policy constitutes acceptance of those changes. If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us using the information provided below. We value your privacy and are committed to safeguarding your personal information. We may update this Privacy Policy periodically to reflect changes in our privacy practices or legal requirements. It is your responsibility to review this Privacy Policy periodically for updates. By continuing to use our website after any changes to this Privacy Policy, you acknowledge and agree to be bound by the updated terms. If you do not agree to the updated terms, you must immediately cease using our website and notify us of your decision. We are committed to protecting your privacy and will continue to take all necessary measures to ensure the security and confidentiality of your personal information. We encourage you to review this Privacy Policy periodically to stay informed about how we collect, use, and protect your personal information. Your continued use of our website following any changes to this Privacy Policy indicates your acceptance of those changes. If you have any questions or concerns about this Privacy Policy or our privacy practices, please contact us using the information provided below. We appreciate your trust in us and thank you for your continued support."
    },
    {
    key: "7",
    label: "Contact Us",
    content: "Feel free to reach out to us via email at contact@example.com or by filling out the contact form on our website. Our dedicated team is here to assist you with any inquiries, feedback, or concerns you may have regarding our products or services. Whether you have questions about placing an order, need assistance with a technical issue, or simply want to share your thoughts with us, we're committed to providing prompt and helpful support. Your satisfaction is our top priority, and we strive to ensure that every interaction with our customers is positive and productive. We value your input and are always looking for ways to improve our offerings, so don't hesitate to get in touch. We appreciate your interest in our company and look forward to hearing from you soon!"
    },  
    
  ];
  export default tabs;